#!/usr/bin/env php
<?php

use Illuminate\Contracts\Console\Kernel as ConsoleKernel;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    fwrite(STDERR, "Composer dependencies are missing. Run `composer install` first.\n");
    exit(1);
}

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(ConsoleKernel::class);

$status = $kernel->handle(
    $input = new ArgvInput
);

$kernel->terminate($input, $status);

exit($status);
